### PR TITLE
Update guzzle package in composer.json

### PR DESCRIPTION
**Pull request by Bukashk0zzz**
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

### CODE REVIEW

**Comment by Bukashk0zzz** [comment]
Depend on https://github.com/scrutinizer-ci/ocular/issues/15

**Comment by schmittjoh** [comment]
I think we also need to make some code changes then, no?

**Comment by Bukashk0zzz** [comment]
I think only update composer.lock
I tested every thing with this config and all work. Proof http://take.ms/BncZIX

Also I run phpunit tests and all ok. I checked https://github.com/Bukashk0zzz/ocular/blob/patch-1/src/Scrutinizer/Ocular/Command/CodeCoverage/UploadCommand.php in PhpStrom and it also not find any problem. 

So I think all good.

Maybe good idea delete composer lock from this project?

**Comment by Bukashk0zzz** [comment]
@schmittjoh So maybe you will do this small change and remove annoying message about guzzle in all users that install this package)

**Comment by schmittjoh** [comment]
Yes, makes sense. Sorry for the wait!

**Pull request merged**
