### PR TITLE
Allow use Symfony 5

### PR DESCRIPTION
**Pull request by peter-gribanov**
Symfony 5 is [released](https://github.com/symfony/symfony/releases/tag/v5.0.0). Need add support it.

### CODE REVIEW

**Comment by schmittjoh** [comment]
Thanks!

**Comment by garak** [comment]
Can we get a release with this? Or at least a `branch-alias` in composer.json

**Comment by peter-gribanov** [comment]
@schmittjoh when will the release be with this change?

**Comment by schmittjoh** [comment]
Sorry for the wait here, I've just tagged the release 👍

**Comment by peter-gribanov** [comment]
@schmittjoh thanks :+1:

**Comment by peter-gribanov** [comment]
@schmittjoh sorry. Can you update releases on [Packagist](https://packagist.org/packages/scrutinizer/ocular)? I do not see the [latest release](https://github.com/scrutinizer-ci/ocular/releases/tag/1.7.0) there. Thanks.

image

**Pull request merged**
